version: "3.2"
services:
  ask-db-nlq-cpu:
    image: ask-db-nlq-cpu
    networks: 
        - inside
        - outside
    ports: 
      - "4000:4000"
    volumes:
#need to bind  
      - ./embedding:/wikisql/embedding/:z
      - ./data_model:/data_model/:z
    working_dir: /wikisql
    environment:
      FLASK_APP: api.py
      CORE_NLP_URL: http://corenlp:9000/
    command: bash startapi.sh
  corenlp:
    image: nlpbox/corenlp
    networks: 
      - inside
networks:
  inside:
    internal: true
  outside:
