version: "3.2"
services:
  ask-db-nlq-cpu:
    image: ask-db-nlq-cpu
    networks: 
        - inside
        - outside
    ports: 
      - 5000:5000
    volumes:
#need to bind  
      - ./wikisql:/wikisql
      - ./embedding:/wikisql/embedding
      - ./data_model:/data_model
    working_dir: /wikisql
    environment:
      FLASK_APP: api.py
    command: bash startapi.sh
  corenlp:
    image: nlpbox/corenlp
    networks: 
      - inside
networks:
  inside:
    internal: true
  outside: